### ISSUE TITLE
회원가입 기능 구현

### ISSUE THREAD

**Issue by coldrice99** [interparty/interparty_#2]
### > [POST] /api/auth/signup

---

#### **구현 내용**

- [ ] **User 엔티티 작성**  
  - 사용자 정보를 저장할 엔티티 생성.  
  - 필드: `id`, `username`, `password`, `email`, `nickname`, `userRole`, `phoneNumber`, `isDeleted`.

- [ ] **UserRepository 작성**  
  - 사용자 데이터를 데이터베이스에서 조회 및 저장하는 레포지토리 작성.  
  - 중복 체크를 위한 `findByUsername` 및 `findByEmail` 메소드 포함.

- [ ] **SignupRequestDto 작성**  
  - 회원가입 요청 데이터를 캡슐화하는 DTO 작성.  
  - 필드: `username`, `email`, `password`, `userRole`, `nickname`, `phoneNumber`.

- [ ] **UserService 작성**  
  - 회원가입 로직 구현.  
    - 사용자 이름(`username`)과 이메일(`email`) 중복 확인.  
    - 비밀번호 암호화(`BCryptPasswordEncoder`) 후 저장.  
    - 기본값으로 `isDeleted`는 `false` 설정.  

- [ ] **예외 처리**  
  - 이미 존재하는 사용자 이름 또는 이메일인 경우, `400 Bad Request`로 처리.  
  - 필수 데이터 누락 시 적절한 에러 메시지 반환.  

---

#### **예외 처리**
- **중복 확인**: 
  - `username` 또는 `email`이 이미 존재할 경우.  
  - 반환: `400 Bad Request` (`"이미 존재하는 사용자입니다."`).

- **필수 데이터 누락**: 
  - 요청 데이터에 필수 필드가 비어 있을 경우.  
  - 반환: `400 Bad Request` (`"입력값이 유효하지 않습니다."`).

---

#### **그 밖의 세부 사항**
- `userRole`은 Enum으로 관리하며 기본값은 `USER`.  
- `isDeleted` 필드는 회원 탈퇴 시 `true`로 변경.  
- 향후 관리자 계정을 생성할 때 추가적인 검증 로직을 고려.  

---

### `RequestBody`
```json
{
  "username": "testuser",
  "email": "test@example.com",
  "password": "Test@123",
  "userRole": "USER",
  "nickname": "testnick",
  "phoneNumber": "010-1234-5678"
}
```

### `ResponseBody`
**성공 시**  
```json
{
  "message": "회원가입 성공"
}
```

**실패 시 (중복 사용자)**  
```json
{
  "message": "이미 존재하는 사용자입니다."
}
```

**실패 시 (필수 데이터 누락)**  
```json
{
  "message": "입력값이 유효하지 않습니다."
}
```

**Comment by 34-43** [comment]
응답코드 201,409,400 추천
